config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'metrics#index'

  resources :metrics
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/metric.rb
# frozen_string_literal: true

# Metric Model
class Metric < ApplicationRecord
  validates :name, presence: true
  validates :value, presence: true
  validates :timestamp, presence: true

  # @param [DateTime] from
  # @param [DateTime] to
  def self.range(from, to)
    where(timestamp: from..to)
  end

  # @param [DateTime] from
  # @param [DateTime] to
  def self.calculate(from, to)
    if from.present? && to.present?
      range(from, to)
    else
      all
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/metrics_controller.rb
# frozen_string_literal: true

# MetricsController simple CRUD
class MetricsController < ApplicationController
  def index
    from = params[:from].present? ?  params[:from].to_datetime : ''
    to = params[:to].present? ?  params[:to].to_datetime : ''
    metrics = Metric.calculate(from, to)
    @metrics = metrics.group(:name).send("group_by_#{resolve_grouping}".to_sym, :timestamp).average(:value)
  end

  def show
    @metric = Metric.find(params[:id])
  end

  def new
    @metric = Metric.new
  end

  def create
    @metric = Metric.new(metric_params)
    if @metric.save
      redirect_to metrics_path
    else
      render :new
    end
  end

  private

  def resolve_grouping
    return params[:group_by] if %w[minute hour day].include?(params[:group_by])

    'day'
  end

  def metric_params
    params.require(:metric).permit(:name, :value, :timestamp)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/metrics_helper.rb
# frozen_string_literal: true

module MetricsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MetricProyect</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %> 
  </head>

  <body>
    <div class="container">
      <div class="row">
        <div class="col">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/metrics/index.html.erb
<h1>Metrics</h1>

<h3><%= link_to( "New Metric", new_metric_path) %></h3>

<%= line_chart @metrics %>

<div class="row">
    <div class="col">
        <%= form_with method: :get, class: "row gy-2 gx-3 align-items-center" do |form| %>
            <div class="col-auto">
                <%= form.label :from %>
            </div>
            <div class="col-auto">
                <%= form.datetime_field :from, class: "form-control", value: params[:from] %>
            </div>

            <div class="col-auto">
                <%= form.label :to %>
            </div>
            <div class="col-auto">
                <%= form.datetime_field :to, class: "form-control", value: params[:to] %>
            </div>

            <div class="col-auto">
                <%= form.label :group_by %>
            </div>
            <div class="col-auto">
                <%= form.select :group_by, [["Days", "day"], ["Hours", "hour"], ["Minutes", "minute"] ], class: "form-control", selected: params[:group_by] %>
            </div>
            <div class="col-auto">
                <%= form.submit "Filter", class: "btn btn-primary" %>
            </div>
        <% end %>
    </div>
</div>

app/views/metrics/new.html.erb
<h1>New Metric</h1>

<%= form_with model: @metric do |form| %>
  <div class="row mb-3">
    <%= form.label :name, class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
    <%= form.text_field :name, class: "form-control", required: true %>
    </div>
  </div>

  <div class="row mb-3">
    <%= form.label :value, class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
    <%= form.number_field :value, class: "form-control", required: true %>
    </div>
  </div>

  <div class="row mb-3">
    <%= form.label :timestamp, class: "col-sm-2 col-form-label" %>
      <div class="col-sm-10">
        <%= form.datetime_field :timestamp, class: "form-control", required: true %>
      </div>
  </div>

  <%= form.submit class: "btn btn-primary" %>

<% end %>